# Generated by Django 5.2.1 on 2025-05-22 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_pedidohistorico'),
    ]

    operations = [
        migrations.AddField(
            model_name='plato',
            name='alergenos',
            field=models.TextField(blank=True, help_text='Alergenos presentes en el plato'),
        ),
        migrations.AddField(
            model_name='plato',
            name='calorias',
            field=models.IntegerField(blank=True, help_text='Cantidad de calorías', null=True),
        ),
        migrations.AddField(
            model_name='plato',
            name='carbohidratos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='plato',
            name='estado',
            field=models.CharField(choices=[('NUEVO', 'Nuevo'), ('DESCUENTO', 'Descuento')], default='NUEVO', max_length=10),
        ),
        migrations.AddField(
            model_name='plato',
            name='grasa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='plato',
            name='grupo',
            field=models.CharField(choices=[('CARNE', 'Carnes'), ('VERDURA', 'Verduras'), ('PESCADO', 'Pescados'), ('OTROS', 'Otros')], default='OTROS', max_length=20),
        ),
        migrations.AddField(
            model_name='plato',
            name='ingredientes',
            field=models.TextField(blank=True, help_text='Lista de ingredientes del plato'),
        ),
        migrations.AddField(
            model_name='plato',
            name='kilogramos',
            field=models.DecimalField(decimal_places=2, default=0.5, max_digits=5),
        ),
        migrations.AddField(
            model_name='plato',
            name='precio_sin_iva',
            field=models.DecimalField(decimal_places=2, default=5.99, max_digits=6),
        ),
        migrations.AddField(
            model_name='plato',
            name='proteinas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='plato',
            name='sodio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='plato',
            name='vida_util',
            field=models.CharField(default='5 días', max_length=100),
        ),
    ]
