# Generated by Django 5.2.1 on 2025-05-22 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_plato_alergenos_plato_calorias_plato_carbohidratos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plato',
            name='estado',
            field=models.CharField(choices=[('NUEVO', 'Nuevo'), ('DESCUENTO', 'Descuento'), ('COMUN', 'Común')], default='NUEVO', max_length=10),
        ),
    ]
