# Generated by Django 5.2.1 on 2025-05-23 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_cliente_descripcion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='nit',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='telefono',
        ),
        migrations.AddField(
            model_name='empresa',
            name='cif',
            field=models.CharField(default='CIF-PENDIENTE', max_length=20, unique=True, verbose_name='CIF'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empresa',
            name='direccion',
            field=models.TextField(blank=True, null=True, verbose_name='Dirección de entrega'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='plato',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
