# Generated by Django 5.2.1 on 2025-05-23 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_empresa_nit_remove_empresa_telefono_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='cif',
            field=models.CharField(max_length=50),
        ),
    ]
