# Generated by Django 5.2.1 on 2025-05-23 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_empresa_cif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='cif',
            field=models.CharField(max_length=20, unique=True, verbose_name='CIF'),
        ),
    ]
