# Generated by Django 5.2.1 on 2025-05-23 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_empresa_codigo_plato_codigo_alter_empresa_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plato',
            name='estado',
            field=models.CharField(choices=[('NUEVO', 'Nuevo'), ('PREMIUM', 'Premium'), ('DESCUENTO', 'Descuento'), ('COMUN', 'Común')], default='NUEVO', max_length=10),
        ),
    ]
