# Generated by Django 5.2.1 on 2025-05-23 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_plato_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plato',
            name='estado',
            field=models.CharField(choices=[('NUEVO', 'Nuevo'), ('DESCUENTO', 'Descuento'), ('COMUN', 'Común')], default='NUEVO', max_length=10),
        ),
    ]
