# Generated by Django 5.2.1 on 2025-05-26 15:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_plato_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='recibo',
            name='fecha_pago',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recibo',
            name='pagado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='carritoitem',
            name='dia_semana',
            field=models.CharField(choices=[('LUN', 'Lunes'), ('MAR', 'Martes'), ('MIE', 'Miércoles'), ('JUE', 'Jueves'), ('VIE', 'Viernes'), ('SAB', 'Sábado')], default='LUN', max_length=3),
        ),
        migrations.AlterField(
            model_name='disponibilidadplato',
            name='dia',
            field=models.CharField(choices=[('LUN', 'Lunes'), ('MAR', 'Martes'), ('MIE', 'Miércoles'), ('JUE', 'Jueves'), ('VIE', 'Viernes'), ('SAB', 'Sábado')], default='LUN', max_length=3),
        ),
        migrations.AlterField(
            model_name='pedidohistorico',
            name='dia_semana',
            field=models.CharField(choices=[('LUN', 'Lunes'), ('MAR', 'Martes'), ('MIE', 'Miércoles'), ('JUE', 'Jueves'), ('VIE', 'Viernes'), ('SAB', 'Sábado')], max_length=3),
        ),
        migrations.AlterField(
            model_name='plato',
            name='carbohidratos',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='plato',
            name='estado',
            field=models.CharField(choices=[('NUEVO', 'Nuevo'), ('PLATO DE LA SEMANA', 'Plato de la semana'), ('DESCUENTO', 'Descuento'), ('COMUN', 'Común')], default='NUEVO', max_length=30),
        ),
        migrations.AlterField(
            model_name='plato',
            name='grasa',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='plato',
            name='grupo',
            field=models.CharField(choices=[('CARNE', 'Carnes'), ('TORTILLAS', 'Tortillas'), ('PLATO DE CUCHARA', 'Platos de cucharas'), ('ENSALADA Y VERDURA', 'Ensalada y Verduras'), ('PESCADO', 'Pescados'), ('ARROCES Y PASTAS', 'Arroces y pastas')], default='OTROS', max_length=20),
        ),
        migrations.AlterField(
            model_name='plato',
            name='kilogramos',
            field=models.DecimalField(decimal_places=0, default=0.5, max_digits=5),
        ),
        migrations.AlterField(
            model_name='plato',
            name='proteinas',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='plato',
            name='sodio',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='recibo',
            name='fecha_compra',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='recibo',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
