# Generated by Django 5.2.1 on 2025-05-27 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_recibo_fecha_pago_recibo_pagado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recibo',
            name='estado_pago',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('completado', 'Completado'), ('fallido', 'Fallido')], default='pendiente', max_length=30),
        ),
        migrations.AddField(
            model_name='recibo',
            name='metodo_pago',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='recibo',
            name='referencia_pago',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='recibo',
            name='url_iframe',
            field=models.URLField(blank=True, help_text='URL del iframe de Paycomet', null=True),
        ),
    ]
