# Generated by Django 5.2.1 on 2025-08-01 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_recibo_estado_pago_recibo_metodo_pago_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_disponible', models.PositiveIntegerField(default=0, help_text='Cantidad disponible en inventario')),
                ('cantidad_reservada', models.PositiveIntegerField(default=0, help_text='Cantidad reservada para pedidos')),
                ('fecha_produccion', models.DateField(help_text='Fecha de producción del lote')),
                ('fecha_vencimiento', models.DateField(help_text='Fecha de vencimiento')),
                ('ubicacion', models.CharField(blank=True, help_text='Ubicación física del inventario', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='myapp.plato')),
            ],
            options={
                'verbose_name': 'Inventario',
                'verbose_name_plural': 'Inventarios',
                'ordering': ['fecha_vencimiento', 'fecha_produccion'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('ENTRADA', 'Entrada (Producción)'), ('SALIDA', 'Salida (Venta)'), ('AJUSTE', 'Ajuste de Inventario'), ('MERMA', 'Merma/Desperdicio')], max_length=20)),
                ('cantidad', models.IntegerField(help_text='Cantidad (positiva para entrada, negativa para salida)')),
                ('motivo', models.CharField(help_text='Motivo del movimiento', max_length=200)),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True)),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='myapp.inventario')),
                ('recibo', models.ForeignKey(blank=True, help_text='Recibo relacionado (si es venta)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.recibo')),
                ('usuario_responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
                'ordering': ['-fecha_movimiento'],
            },
        ),
        migrations.CreateModel(
            name='Produccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_planificada', models.PositiveIntegerField(help_text='Cantidad planificada a producir')),
                ('cantidad_producida', models.PositiveIntegerField(default=0, help_text='Cantidad realmente producida')),
                ('fecha_planificada', models.DateField(help_text='Fecha planificada de producción')),
                ('fecha_inicio', models.DateTimeField(blank=True, help_text='Fecha y hora de inicio de producción', null=True)),
                ('fecha_completada', models.DateTimeField(blank=True, help_text='Fecha y hora de finalización', null=True)),
                ('estado', models.CharField(choices=[('PLANIFICADA', 'Planificada'), ('EN_PROCESO', 'En Proceso'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='PLANIFICADA', max_length=20)),
                ('costo_ingredientes', models.DecimalField(decimal_places=2, default=0, help_text='Costo total de ingredientes', max_digits=8)),
                ('costo_mano_obra', models.DecimalField(decimal_places=2, default=0, help_text='Costo de mano de obra', max_digits=8)),
                ('otros_costos', models.DecimalField(decimal_places=2, default=0, help_text='Otros costos de producción', max_digits=8)),
                ('notas', models.TextField(blank=True, help_text='Notas adicionales sobre la producción')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producciones', to='myapp.plato')),
                ('responsable', models.ForeignKey(blank=True, help_text='Responsable de la producción', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Producción',
                'verbose_name_plural': 'Producciones',
                'ordering': ['-fecha_planificada', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='inventario',
            name='produccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventario_generado', to='myapp.produccion'),
        ),
    ]
